name: 微证券2

on:
  workflow_dispatch:
  schedule:
     - cron: '0 10 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行【微证券】2'     
        run: |
          node Task/txwzq.js
        env:
          txwzq_txwzqck: ${{ secrets.txwzq_txwzqck2 }}
          txzxg_txzxgck: ${{ secrets.txzxg_txzxgck2 }}
